exp_name: 'SMARL'
gpu_id: [0]
logger:
    display_id: 9908
model:
    change_detector:
        input_dim: 2048 + 4
        feat_dim: 1024+2
        att_dim: 256
        att_head: 4

    speaker:
        word_embed_size: 300
        embed_input_dim: 768
        rnn_size: 512
        embed_dim: 512

        input_dim: 256
        vocab_size: 76
        seq_length: 23

data:
    dataset: 'rcc_dataset_pos'
    vocab_json: './data/vocab.json'
    h5_label_file: './data/labels.h5'
    type_mapping_json: './data/type_mapping.json'
    train:
        batch_size: 128
train:
    max_iter: 10000
    optim:
        type: 'adam'
        lr: 0.0005
        weight_decay: 0.0

